// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilnzyylkrpblquqzpqur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsbnp5eWxrcnBibHF1cXpwcXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTc5NjcsImV4cCI6MjA2NzQzMzk2N30.Mq5CwYQ_7x6IzeHYOj94dh3z_D_tIjTDA-ZJau5hhuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});